### ISSUE TITLE
Implement proper variant support on Button component

### ISSUE THREAD

**Issue by benslv** [yordevs/yordevs.github.io#28]
I didn't see this before but `styled-components` actually supports a proper Variants system, so we don't need to do the janky stuff with passing a prop in. This also means it supports more than two variants really easily.

https://styled-components.com/docs/tooling#themevariantsname-prop-themes

**Comment by silverben10** [comment]
Have looked into this more and variants are actually part of a much large `styled-themeing` system. We can basically convert everything that's currently in `theme/config.js` into something that `styled-theming` looks at, and then have different versions for light and dark theme. 
Not entirely sure this is as simple as I first thought it was, so it'll be put on the backburner for now while we sort the rest of the site, I think.

**Comment by benslv** [comment]
Closing this ticket for the time being because it's really very low priority and not an issue unless we want to start adding more types of buttons.
