### ISSUE TITLE
Optimise images on Meet the Team page

### ISSUE THREAD

**Issue by benslv** [yordevs/yordevs.github.io#34]
I've noticed the profil images are quite slow to load when viewing the *Meet the Team* page (if they aren't already cached). It looks like the images are around 200-300KB, and I think they could definitely do with being optimised a bit more so they load quicker.

Given we already support Gatsby Image on this site, I think the best thing to do is to simply implement that on the *Meet the Team* page. Failing that, if we can just chuck the images through something like [compressjpeg.com](http://compressjpeg.com) that would massively improve their loading times.

**Comment by 4dambarr** [comment]
You can't use gatsby static images for this as they paths are being passed as parameters to the card and it looks like the src value needs to be there on load time for it to work with static images, can't remember if I tested dynamic ones

**Comment by silverben10** [comment]
I think you're right, yeah. With the way we currently do it we'd probably need to take a look at dynamic images and see if we can implement them. It would require some GraphQL queries on the *Meet the Team* page to pull the relevant images, I think.

One thing I did wonder is whether we could try passing a `<StaticImage />` component as the `picture` prop for `CommitteeCard`? That way we could hardcode the image into each component and would be able to easily fix it.

*Example:*
```
<CommitteeCard
  fullName="Joe Bloggs"
  role="Example"
  pronouns="He/Him"
  course="Computer Science"
  picture={<StaticImage src={JoePicture} />}
/>
```

**Comment by silverben10** [comment]
Would require a teeny bit of refactoring of the `CommitteeCard` component (and then also the `ProjectLeaderCard` component once we get it working) but I have a feeling it's a good compromise between not duplicating too much code but also making our lives a little easier.
