### ISSUE TITLE
Deploy website to Vercel

### ISSUE THREAD

**Issue by benslv** [yordevs/yordevs.github.io#55]
Vercel would be a good place to deploy our site to, to get a bunch of useful features like:
- automatic preview builds for every PR
- site analytics
- built-in site performance metrics

Think it should be as simple as creating a Vercel account for the society (or just a personal one for yourself) and linking the branch and repo to it.

**Comment by 4dambarr** [comment]
Vercel requires a paid account to deploy organisation websites, right now this is not feasible for us
