### ISSUE TITLE
Link to GitHub repo somewhere more visible

### ISSUE THREAD

**Issue by benslv** [yordevs/yordevs.github.io#76]

**Comment by SJellen** [comment]
<img width="923" alt="Screen Shot 2021-05-23 at 11 47 07 AM" src="https://user-images.githubusercontent.com/51421669/119267509-ed097d80-bbbc-11eb-9a76-897da824efaa.png">

**Comment by 4dambarr** [comment]
Probably a good shout, also maybe it is worth linking to [https://github.com/yordevs](https://github.com/yordevs) as opposed to this repo directly
